### ISSUE TITLE
A very recent version of glibc (2.38) is required

### ISSUE THREAD

**Issue by steven-joruk** [kidonng/notion-appimage#1]
Hey, thanks for sharing your repack. I tried using your AppImage with Ubuntu 22.04, which ships with [glibc 2.35](https://launchpad.net/ubuntu/jammy/+source/glibc). It would be great if you could depend on a glibc version that ships with Ubuntu's latest LTS.

Here are the logs:
```
./Notion-2.2.1-1-x86_64.AppImage 
[1026/140555.560961:ERROR:file_io_posix.cc(152)] open /home/steven/.config/Notion/Crashpad/pending/0c670aed-1831-4ca0-a712-40e0d45b3778.lock: File exists (17)
14:05:55.754 (AutoUpdater) › Checking for update
14:05:55.762               › App starting with version 2.2.1 { system: 'linux x64', electron: '26.2.4' }
14:05:56.015 (AutoUpdater) › Error: Error: ENOENT: no such file or directory, open '/tmp/.mount_NotionQTk1Ho/resources/app-update.yml'
14:05:56.017 (AssetCache)  › Error reading and parsing JSON {
  error: "Error: ENOENT: no such file or directory, open '/home/steven/.config/Notion/notionAssetCache-v2/latestVersion.json'",
  absolutePath: '/home/steven/.config/Notion/notionAssetCache-v2/latestVersion.json'
}
14:05:56.020               › {
  os: 'unknown',
  platform: 'electron',
  desktopVersion: '2.2.1',
  desktopCPU: '12th Gen Intel(R) Core(TM) i9-12900K',
  desktopRAM: '31G',
  environment: 'production',
  level: 'error',
  from: 'AssetCache',
  type: 'failedToReadDir',
  error: {
    name: 'Error',
    message: "ENOENT: no such file or directory, scandir '/home/steven/.config/Notion/notionAssetCache-v2'",
    stack: "Error: ENOENT: no such file or directory, scandir '/home/steven/.config/Notion/notionAssetCache-v2'",
    miscDataString: '{"dirPath":"/home/steven/.config/Notion/notionAssetCache-v2"}'
  }
}
14:05:56.070 (Sqlite)      › Child process running on 36159
14:05:56.215                 › App is visible: true
14:05:56.352 (Sqlite)        › stderr: /tmp/.mount_NotionQTk1Ho/resources/app.asar/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.org.chromium.Chromium.5sYVvR)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2131)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2358)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at bindings (/tmp/.mount_NotionQTk1Ho/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at new Database (/tmp/.mount_NotionQTk1Ho/resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by kidonng** [comment]
Please try [the latest release](https://github.com/kidonng/notion-appimage/releases/tag/2.2.4-1) and let me know if it works for you! (At least works for me:tm:)
